#!/usr/bin/env python3
"""Generate optional publication tables from final prospective simulation JSON."""
import argparse
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent


def table(caption, label, columns, heading, rows, note):
    return '\n'.join([
        '% Generated by power_tables.py; prospective simulations only.',
        r'\begin{table}[htbp]', r'\singlespacing', r'\centering', r'\small',
        '\\caption{'+caption+'}', '\\label{'+label+'}',
        '\\begin{tabular}{'+columns+'}', r'\toprule', heading+r' \\',
        r'\midrule', *[r' & '.join(row)+r' \\' for row in rows],
        r'\bottomrule', r'\end{tabular}', r'\par\smallskip',
        '\\begin{minipage}{.98\\linewidth}\\footnotesize '+note+r'\end{minipage}',
        r'\end{table}', ''])


def main():
    ap=argparse.ArgumentParser()
    ap.add_argument('--input',type=Path,default=HERE/'results/power/final_power_results.json')
    ap.add_argument('--output-dir',type=Path,default=HERE/'results/power/tables')
    args=ap.parse_args()
    data=json.loads(args.input.read_text())
    assert data['design']['gamma_probabilities']==[.4,.2,.4]
    assert data['design']['primary'].startswith('near endpoint <0 AND far endpoint >0')
    args.output_dir.mkdir(parents=True,exist_ok=True)
    common=(r'Each row uses 10,000 simulated studies, 300 participants in 150 pairs, '
            r'24 rounds, fee probabilities $(.5,.5)$, friction probabilities $(.4,.2,.4)$ '
            r'for $\gamma=(0,2,4)$, and 10\% whole-person MCAR observation loss. '
            r'All figures are prospective, conditional on the stated behavioural model; '
            r'$\omega$ is assumed, not estimated. ')
    mainrows=[]; secrows=[]; stressrows=[]; meansrows=[]
    md=['# Final prospective simulation tables', '',
        'No participant or pilot data. All rates use 10,000 studies per row.', '',
        '| DGP | Assumed omega | Mean near endpoint | Mean far endpoint | Primary joint signs | MCSE | Secondary interaction, Holm | Depth equivalence, Holm | Conversion equivalence, Holm | CS advantage, Holm |',
        '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |']
    for group in ('base','strong_persistence'):
        for scenario in data[group]['scenarios'].values():
            assert scenario['replications']==10000
            a=f"{scenario['alpha_assumed']:g}"
            effect=scenario['effect_mean']
            p=scenario['primary_joint_signs']
            h=scenario['secondary_Holm_adjusted']['rate']
            md.append('| '+' | '.join([group,a,f'{effect[1]:.6f}',f'{effect[2]:.6f}',
                f"{p['rate']:.4f}",f"{p['Monte_Carlo_SE']:.6f}",*[f'{q:.4f}' for q in h]])+' |')
            if group=='base':
                mainrows.append([a,f'{effect[1]:.3f}',f'{effect[2]:.3f}',f'{effect[0]:.3f}',
                                 f"{p['rate']:.4f}",f"{p['Monte_Carlo_SE']:.5f}"])
                secrows.append([a,*[f'{q:.4f}' for q in h]])
                meansrows.append([a,f'{effect[3]:.4f}',*[f'{100*effect[q]:.3f}' for q in (4,5,6)],f'{effect[7]:.3f}'])
            else:
                stressrows.append([a,f"{p['rate']:.4f}",f"{p['Monte_Carlo_SE']:.5f}",*[f'{q:.4f}' for q in h]])
    primarynote=(common+r'$\Delta_N$ and $\Delta_F$ are mean simulated $\gamma=4$ minus $\gamma=0$ depth contrasts, '
                 r'and $\theta=\Delta_F-\Delta_N$. The primary intersection--union test rejects only when '
                 r'both one-sided CR2 component tests reject at 5\%; its $p$-value is their maximum, without Holm adjustment. '
                 r'The $\omega=0$ primary entry is a both-zero-null rejection rate, not a worst-case size assessment. '
                 r'MCSE is the Monte Carlo standard error of the rejection rate.')
    secondarynote=(common+r'The four secondary tests form one fixed Holm-adjusted family at 5\%, with no gate on primary rejection. '
                   r'Depth equivalence uses margin $0.25$ openings at $\gamma=0$; conversion equivalence uses margin '
                   r'$0.05$ at each of the three friction levels and requires all three. '
                   r'The surplus contrast is nearest minus farthest, equally averaging positive friction levels. '
                   r'Unestimable claims count as non-rejections. '
                   r'$\omega=0$ is not a joint null for these secondary hypotheses.')
    (args.output_dir/'primary_power.tex').write_text(table(
        'Prospective power for the primary joint-sign claim', 'tab:final-joint-power','rrrrrr',
        r'$\omega$ & $\Delta_N$ & $\Delta_F$ & $\theta$ & Joint-sign rate & MCSE',mainrows,primarynote))
    (args.output_dir/'secondary_power.tex').write_text(table(
        'Prospective rejection rates for the secondary family','tab:final-secondary-power','rrrrr',
        r'$\omega$ & Interaction & Depth equivalence & Conversion equivalence & Surplus advantage',secrows,secondarynote))
    (args.output_dir/'secondary_means.tex').write_text(table(
        'Simulated mean secondary contrasts','tab:final-secondary-means','rrrrrr',
        r'$\omega$ & Depth, $\gamma=0$ & Conversion, $\gamma=0$ & $\gamma=2$ & $\gamma=4$ & Surplus',meansrows,
        common+r'Depth and conversion contrasts are farthest minus nearest. Conversion differences are percentage points. '
        r'Surplus is nearest minus farthest at positive friction levels, in experimental points. '
        r'Fee levels and relevant friction levels receive equal weight, despite unequal friction assignment probabilities. '
        r'Means use inference-estimable studies only; exact counts and Monte Carlo errors are in the machine-readable results.'))
    (args.output_dir/'strong_persistence_power.tex').write_text(table(
        'Prospective rejection rates under stronger behavioural persistence','tab:final-strong-power','rrrrrrr',
        r'$\omega$ & Joint signs & MCSE & Interaction & Depth equiv. & Conv. equiv. & Surplus',stressrows,
        common+r'This scenario uses attention concentration $0.5$ and an inattention branch consisting entirely of '
        r'a participant-specific fixed depth, rather than concentration $5$ and a half fixed-depth, half friction-blind mixture. '
        r'Joint signs are primary; the last four columns use the fixed secondary Holm family. '
        r'Unestimable claims count as non-rejections. '
        r'The primary $\omega=0$ row is a both-zero-null rejection rate, not a worst-case size assessment.'))
    md+=['', 'Secondary columns are Holm-adjusted in one fixed family. They are not gated by primary rejection.', '',
         'All primary and endpoint contrasts were estimable. Rejection rates retain them as non-rejections.', '',
         'Means condition on estimability. The saved arrays and JSON contain all contrast standard errors, degrees of freedom, outcome cell means, counts and Monte Carlo standard errors. The omega=0 primary rate is a both-zero-null diagnostic, not a worst-case IUT size assessment.', '']
    (args.output_dir/'table_values.md').write_text('\n'.join(md))
    print(f'Wrote four TeX tables and one Markdown value table under {args.output_dir}')


if __name__=='__main__': main()
